# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/heartsurfacewidget.ui'
#
# Created: Sun Jul 26 13:58:01 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_HeartSurfaceWidget(object):
    def setupUi(self, HeartSurfaceWidget):
        HeartSurfaceWidget.setObjectName("HeartSurfaceWidget")
        HeartSurfaceWidget.resize(1021, 620)
        self.horizontalLayout = QtGui.QHBoxLayout(HeartSurfaceWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtGui.QGroupBox(HeartSurfaceWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButtonLoad = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout_8.addWidget(self.pushButtonLoad)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButtonSave = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_9.addWidget(self.pushButtonSave)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.line = QtGui.QFrame(self.groupBox_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButtonContinue = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonContinue.setObjectName("pushButtonContinue")
        self.horizontalLayout_7.addWidget(self.pushButtonContinue)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_10.addWidget(self.groupBox_4)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonViewAll = QtGui.QPushButton(self.groupBox_6)
        self.pushButtonViewAll.setObjectName("pushButtonViewAll")
        self.horizontalLayout_2.addWidget(self.pushButtonViewAll)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButtonHideAll = QtGui.QPushButton(self.groupBox_6)
        self.pushButtonHideAll.setObjectName("pushButtonHideAll")
        self.horizontalLayout_6.addWidget(self.pushButtonHideAll)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.listWidget = QtGui.QListWidget(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_9.addWidget(self.listWidget)
        self.verticalLayout_10.addWidget(self.groupBox_6)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.spinBoxPointSize = QtGui.QSpinBox(self.groupBox_5)
        self.spinBoxPointSize.setMinimum(1)
        self.spinBoxPointSize.setObjectName("spinBoxPointSize")
        self.horizontalLayout_10.addWidget(self.spinBoxPointSize)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.comboBoxHeartSurface = QtGui.QComboBox(self.groupBox_5)
        self.comboBoxHeartSurface.setObjectName("comboBoxHeartSurface")
        self.comboBoxHeartSurface.addItem("")
        self.comboBoxHeartSurface.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBoxHeartSurface)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.verticalLayout_10.addWidget(self.groupBox_5)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.widgetZinc = SegmentationWidget(HeartSurfaceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetZinc.sizePolicy().hasHeightForWidth())
        self.widgetZinc.setSizePolicy(sizePolicy)
        self.widgetZinc.setObjectName("widgetZinc")
        self.horizontalLayout.addWidget(self.widgetZinc)

        self.retranslateUi(HeartSurfaceWidget)
        QtCore.QMetaObject.connectSlotsByName(HeartSurfaceWidget)

    def retranslateUi(self, HeartSurfaceWidget):
        HeartSurfaceWidget.setWindowTitle(QtGui.QApplication.translate("HeartSurfaceWidget", "Heart Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("HeartSurfaceWidget", "Heart Surface Segmenter", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("HeartSurfaceWidget", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLoad.setText(QtGui.QApplication.translate("HeartSurfaceWidget", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setText(QtGui.QApplication.translate("HeartSurfaceWidget", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonContinue.setText(QtGui.QApplication.translate("HeartSurfaceWidget", "Continue", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("HeartSurfaceWidget", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonViewAll.setText(QtGui.QApplication.translate("HeartSurfaceWidget", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonHideAll.setText(QtGui.QApplication.translate("HeartSurfaceWidget", "Hide All", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("HeartSurfaceWidget", "Segmentation", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HeartSurfaceWidget", "Point size: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("HeartSurfaceWidget", "Heart surface: ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHeartSurface.setItemText(0, QtGui.QApplication.translate("HeartSurfaceWidget", "Endocardial", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHeartSurface.setItemText(1, QtGui.QApplication.translate("HeartSurfaceWidget", "Epicardial", None, QtGui.QApplication.UnicodeUTF8))

from segmentationwidget import SegmentationWidget
