# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/heartsurfacewidget.ui'
#
# Created: Fri May 22 23:43:04 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_HeartSurfaceWidget(object):
    def setupUi(self, HeartSurfaceWidget):
        HeartSurfaceWidget.setObjectName("HeartSurfaceWidget")
        HeartSurfaceWidget.resize(729, 518)
        self.horizontalLayout = QtGui.QHBoxLayout(HeartSurfaceWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dockWidget = QtGui.QDockWidget(HeartSurfaceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setStyleSheet("QToolBox::tab {\n"
"         background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                     stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                     stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"         border-radius: 5px;\n"
"         color: black;\n"
"     }\n"
"\n"
"     QToolBox::tab:selected { /* italicize selected tabs */\n"
"         font: bold;\n"
"         color: black;\n"
"     }\n"
"QToolBox {\n"
"    padding : 0\n"
"}")
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtGui.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtGui.QToolBox(self.dockWidgetContents)
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setObjectName("toolBox")
        self.pageFile = QtGui.QWidget()
        self.pageFile.setGeometry(QtCore.QRect(0, 0, 163, 397))
        self.pageFile.setObjectName("pageFile")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pageFile)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonSave = QtGui.QPushButton(self.pageFile)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_4.addWidget(self.pushButtonSave)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonLoad = QtGui.QPushButton(self.pageFile)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout_5.addWidget(self.pushButtonLoad)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtGui.QSpacerItem(20, 146, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonDone = QtGui.QPushButton(self.pageFile)
        self.pushButtonDone.setObjectName("pushButtonDone")
        self.horizontalLayout_3.addWidget(self.pushButtonDone)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.toolBox.addItem(self.pageFile, "")
        self.pageView = QtGui.QWidget()
        self.pageView.setGeometry(QtCore.QRect(0, 0, 163, 397))
        self.pageView.setObjectName("pageView")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pageView)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonViewAll = QtGui.QPushButton(self.pageView)
        self.pushButtonViewAll.setObjectName("pushButtonViewAll")
        self.horizontalLayout_2.addWidget(self.pushButtonViewAll)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.listWidget = QtGui.QListWidget(self.pageView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        spacerItem6 = QtGui.QSpacerItem(20, 238, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.toolBox.addItem(self.pageView, "")
        self.pageSegmentation = QtGui.QWidget()
        self.pageSegmentation.setObjectName("pageSegmentation")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pageSegmentation)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtGui.QGroupBox(self.pageSegmentation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.spinBoxPointSize = QtGui.QSpinBox(self.groupBox)
        self.spinBoxPointSize.setMinimum(1)
        self.spinBoxPointSize.setObjectName("spinBoxPointSize")
        self.verticalLayout_4.addWidget(self.spinBoxPointSize)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.pageSegmentation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBoxHeartSurface = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxHeartSurface.setGeometry(QtCore.QRect(10, 30, 111, 23))
        self.comboBoxHeartSurface.setObjectName("comboBoxHeartSurface")
        self.comboBoxHeartSurface.addItem("")
        self.comboBoxHeartSurface.addItem("")
        self.verticalLayout_5.addWidget(self.groupBox_2)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.toolBox.addItem(self.pageSegmentation, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout.addWidget(self.dockWidget)
        self.widgetZinc = SegmentationWidget(HeartSurfaceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetZinc.sizePolicy().hasHeightForWidth())
        self.widgetZinc.setSizePolicy(sizePolicy)
        self.widgetZinc.setObjectName("widgetZinc")
        self.horizontalLayout.addWidget(self.widgetZinc)

        self.retranslateUi(HeartSurfaceWidget)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HeartSurfaceWidget)

    def retranslateUi(self, HeartSurfaceWidget):
        HeartSurfaceWidget.setWindowTitle(QtGui.QApplication.translate("HeartSurfaceWidget", "Heart Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("HeartSurfaceWidget", "Heart Surface &Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setText(QtGui.QApplication.translate("HeartSurfaceWidget", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLoad.setText(QtGui.QApplication.translate("HeartSurfaceWidget", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDone.setText(QtGui.QApplication.translate("HeartSurfaceWidget", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageFile), QtGui.QApplication.translate("HeartSurfaceWidget", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonViewAll.setText(QtGui.QApplication.translate("HeartSurfaceWidget", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageView), QtGui.QApplication.translate("HeartSurfaceWidget", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("HeartSurfaceWidget", "Point size", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("HeartSurfaceWidget", "Heart Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHeartSurface.setItemText(0, QtGui.QApplication.translate("HeartSurfaceWidget", "Endocardial", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHeartSurface.setItemText(1, QtGui.QApplication.translate("HeartSurfaceWidget", "Epicardial", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageSegmentation), QtGui.QApplication.translate("HeartSurfaceWidget", "Segmentation", None, QtGui.QApplication.UnicodeUTF8))

from segmentationwidget import SegmentationWidget
